### PR TITLE
enable Scala 2.13.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@gheine this library does not compile in Scala 2.13.0 due to [scala.collection.mutable.ArraySeq] usage

**Comment by sullis** [comment]
@gheine  this library doesn't compile in Scala 2.13.x --- can you fix this?

**Comment by gheine** [comment]
Oh, got it. Will take a look @sullis

**Comment by sullis** [comment]
@gheine this library does not compile in Scala 2.13.1 due to [scala.collection.mutable.ArraySeq] usage

**Pull request closed without merging**
